# This is a basic workflow to help you get started with Actions

name: github-jobs-deploy

on: 
 push:
  branches: [master]
 pull_request: 
  branches: [master]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: action checkout
        uses: actions/checkout@v2
    
    
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
     
      - name: Install Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
         cmd: install # will run `yarn install` command
 
        
      - name: Build React App
        run: yarn build
      
      - name: Install Surge
        run: npm install --global surge
      
      - name: Deploy to Surge
        run: surge ./build jobapi.surge.sh --token ${{secrets.SURGE_TOKEN}}
